name: Build and Deploy - Sandbox

on:
  push:
    breanches: [sandbox]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Write out google-key.json
        run: 'echo "$GOOG_KEY" > src/main/resources/google-key.json'
        shell: bash
        env:
          GOOG_KEY: ${{ secrets.GOOGLE_KEY }}
      - name: Build mule application
        run: mvn -B package -s .maven/settings.xml
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
          PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
      - name: Deploy mule application to CloudHub environment Sandbox
        run: mvn -B deploy -DmuleDeploy -s .maven/settings.xml
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
          PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
          GOOG_PROJECTID: ${{ secrets.GOOG_PROJECTID }}
          GOOG_SUBID: ${{ secrets.GOOG_SUBID }}
          GOOG_TOPICID: ${{ secrets.GOOG_TOPICID }}
          BUSINESS_GROUP_ID: ${{ secrets.BUSINESS_GROUP_ID }}
          PLATFORM_CLIENT_ID: ${{ secrets.PLATFORM_CLIENT_ID }}
          PLATFORM_CLIENT_SECRET: ${{ secrets.PLATFORM_CLIENT_SECRET }}
          SQL_DB: ${{ secrets.SQL_DB }}
          SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          APP_NAME: sandbox-pubsub-to-synapse-papi-v1
